"""initials migration

Revision ID: 49111ccd81a1
Revises: 
Create Date: 2025-12-03 14:30:30.475452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49111ccd81a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.String(length=36), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('pais',
    sa.Column('pais_id', sa.String(length=36), nullable=False),
    sa.Column('nombre_pais', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pais_id'),
    sa.UniqueConstraint('codigo_iso')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contactos',
    sa.Column('id_contacto', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('id_categoria', sa.String(length=36), nullable=True),
    sa.Column('pais_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.pais_id'], ),
    sa.PrimaryKeyConstraint('id_contacto'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_usuarios_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactos')
    op.drop_table('usuarios')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('pais')
    op.drop_table('categorias')
    # ### end Alembic commands ###
